name: surebuy
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.6
  firebase_core: ^3.8.1
  firebase_analytics: ^11.3.6
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  image_picker: ^1.1.2
  fluttertoast: ^8.2.10
  provider: ^6.0.0
  firebase_app_check: ^0.3.2+4
  local_auth: ^2.3.0
  flutter_secure_storage: ^9.2.4
  flutter_windowmanager_plus: ^1.0.1
  http: ^0.13.6
  url_launcher: ^6.1.14
  webview_flutter: ^4.2.4
  http_interceptor: ^1.0.2
  uni_links5: ^0.5.4
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/surebuy_icon.png
    - assets/img.png
    - assets/app_icon.png
