// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6ahh5df5EAW3ygO3iHQXE2KyfXc4_tp0',
    appId: '1:63493614469:web:c1c1e9cea086aed0b632ec',
    messagingSenderId: '63493614469',
    projectId: 'surebuy-d380d',
    authDomain: 'surebuy-d380d.firebaseapp.com',
    storageBucket: 'surebuy-d380d.firebasestorage.app',
    measurementId: 'G-1KYE08FL2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_xrI5xJAXm_xSicAekGbS6GB8y2ukzeU',
    appId: '1:63493614469:android:cacd1b6d3cd45d45b632ec',
    messagingSenderId: '63493614469',
    projectId: 'surebuy-d380d',
    storageBucket: 'surebuy-d380d.firebasestorage.app',
  );
}
